title: Guías
description: "Guías sobre temas de bases de datos y programación"
url: "https://enidev911.github.io"
base_url: "/guias"
google_analytics:
theme: jekyll-theme-midnight
markdown: kramdown
highlighter: rouge
linenos: true

syntax_highlighter_opts:
  # Rouge Options › https://github.com/jneen/rouge#full-options
  css_class: 'highlight'
  #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
kramdown:
  input: GFM

plugins:
  - jemoji
  - jekyll-tabs

collections:
  bash:
    output: true
  jekyll:
    output: true
  postgres:
    output: true
  javascript:
    output: true
  mysql:
    output: true
  markdown:
    output: true
  ruby:
    output: true
  vscode:
    output: true

collections_dir: docs

defaults:
  -
    scope:
      type: postgres
    values:
      image_path: /assets/images/postgres/
  -
    scope:
      type: mysql
    values:
      image_path: /assets/images/mysql/
  -
    scope:
      type: jekyll
    values:
      image_path: /assets/images/jekyll/