title: Guías
description: "Guías sobre temas de bases de datos y programación"
google_analytics:
theme: jekyll-theme-midnight
markdown: kramdown
highlighter: rouge
linenos: true

syntax_highlighter_opts:
  # Rouge Options › https://github.com/jneen/rouge#full-options
  css_class: 'highlight'
  #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
kramdown:
  input: GFM

plugins:
  - jemoji

collections:
  markdown_papers:
    output: true
    permalink: /markdown/:path